language: node_js
node_js:
- "node"
services:
- mongodb
before_install:
- npm install -g swagger
before_script:
- sleep 15
- mongo evt-xtrm-db --eval 'db.createUser({user: "test", pwd: "test", roles: [ { role: "readWrite", db: "config" } ]});'

