swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  #############################
  # event API START
  ############################
  /api/event:
    x-swagger-router-controller: event
    get:
      description: Returns a list of evnets
      operationId: listEvents
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/EventListResponse"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Create a new event admin permission only
      operationId: createEvent
      parameters:
        - name: title
          in: formData
          description: title of event
          required: true
          type: string
        - name: description
          in: formData
          description: description of event
          required: true
          type: string
        - name: date
          in: formData
          description: date of event
          type: string
          format: date-time
          required: true
        - name: limit
          in: formData
          description: max amount of participants
          type: integer
          required: false
      responses:
        201:
          description: Success
          schema:
            $ref: "#/definitions/EventResponse"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/ErrorResponse"
        
          
          
  /api/event/{id}:
    x-swagger-router-controller: event
    get:
      description: Returns an event
      operationId: getEventById
      parameters:
        - name: id
          in: path
          description: event id
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/EventResponse"
        404:
          description: Not found
          schema:
            $ref: "#/definitions/ErrorResponse"
    
    patch:
      description: partial update need admin permission only
      operationId: updateEventById
      parameters:
        - name: id
          in: path
          description: id of event to patch
          required: true
          type: string
        - name: title
          in: formData
          description: title of event
          required: false
          type: string
        - name: description
          in: formData
          description: description of event
          required: false
          type: string
        - name: date
          in: formData
          description: date of event
          type: string
          format: date-time
          required: false
        - name: limit
          in: formData
          description: max amount of participants
          type: integer
          required: false
      
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/EventResponse"
        404:
          description: Not found
          schema:
            $ref: "#/definitions/ErrorResponse"
        400:
          description: Bad requiest
          schema:
            $ref: "#/definitions/ErrorResponse"
          
    
    delete:
      description: deletes an event admin permission only
      operationId: deleteEventById
      parameters:
        - name: id
          in: path
          description: event id
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: Not found
          schema:
            $ref: "#/definitions/ErrorResponse"
  ##############################
  # event API end
  # participant API start
  ##################################
          
  /api/participant/{event}:
    x-swagger-router-controller: participant
    get:
      description: Lists all participants of an event
      operationId: listParticipantsOnEvent
      parameters:
        - name: event
          in: path
          description: event id
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/ParticipantListResponse"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/ErrorResponse"
    
    post:
      description: Add participant to event
      operationId: postParticipantOnEvent
      parameters:
        - name: event
          in: path
          description: event id
          required: true
          type: string
        - name: user
          in: formData
          description: user id, automatic for other than admins
          type: integer
      responses:
        201:
          description: Success
          schema:
            $ref: "#/definitions/ParticipantResponse"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: remove participant from event
      operationId: deleteParticipantOnEvent
      parameters:
        - name: event
          in: path
          description: event id
          required: true
          type: string
        - name: user
          in: formData
          description: user to remove from event
          type: integer
          required: true
      responses: 
        200:
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: Not found
          schema:
            $ref: "#/definitions/ErrorResponse"
  #######################
  # Participant API end
  #########################
  
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:

####################
### event definitions
####################
  EventResponse:
    required:
      - _id
    properties:
      _id:
        type: string
      title:
        type: string
      description:
        type: string
      date:
        type: string
        format: date-time
      limit:
        type: integer

  EventListResponse:
    required:
      - events
    properties:
      events:
        type: array
        items:
          type: object
          properties:
            _id:
              type: string
            title:
              type: string
            description:
              type: string
            date:
              type: string
              format: date-time
            limit:
              type: integer

#############
## event defenitions end
## participant defenitions start
#########################
  ParticipantListResponse:
    required:
      - participants
    properties:
      participants:
        type: array
        items:
          type: object
          properties:
            _id:
              type: string
            event:
              type: integer
            user:
              type: integer
              
  ParticipantResponse:
    required:
      - _id
    properties:
      _id:
        type: string
      event:
        type: integer
      user:
        type: integer
#############
## participant defenitions end
## common response
##################
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
        
        
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
